<a href="https://colab.research.google.com/github/RixzFahad/Machine-Learning/blob/main/DataAnalysis_Pp_Pulse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#after creating the clone of phonepe h=github then import the libraries

!git clone https://github.com/PhonePe/pulse.git
import pandas as pd
import json
import os #operating system used to access each file directory path

#take path1 as a aggregated transaction data and acces statewise data

path1 = "/content/pulse/data/aggregated/transaction/country/india/state"

agg_state_list = os.listdir(path1)

#agg_state_list

#extract the data to create the dataframe

clm = {'State':[],'Year':[],'quarter':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

for i in agg_state_list:

    #print(i)

    p_i = path1+"/"+i

    agg_yr = os.listdir(p_i)

    #print(agg_yr)

    for j in agg_yr:

        p_j = p_i + "/" + j

        agg_year_quarter = os.listdir(p_j)

        #print(agg_year_quarter)
        for k in agg_year_quarter:

            p_k = p_j + "/" + k

            #print(p_k)

            data = open(p_k,'r')
            D = json.load(data)
            for z in D['data']['transactionData']:

              Name = z['name']
              count = z['paymentInstruments'][0]['count']
              amount = z['paymentInstruments'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['quarter'].append(int(k.strip('.json')))

print(clm)

Cloning into 'pulse'...
remote: Enumerating objects: 17904, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 17904 (delta 19), reused 17 (delta 17), pack-reused 17855 (from 2)
Receiving objects: 100% (17904/17904), 26.13 MiB | 14.96 MiB/s, done.
Resolving deltas: 100% (8723/8723), done.
Updating files: 100% (9029/9029), done.

In [2]:
agg_transactions = pd.DataFrame(clm)

agg_transactions.head()

,State,Year,quarter,Transaction_type,Transaction_count,Transaction_amount
0,maharashtra,2019,2,Peer-to-peer payments,42546317,1.305582e+11
1,maharashtra,2019,2,Recharge & bill payments,29395661,1.219723e+10
2,maharashtra,2019,2,Merchant payments,27854042,9.728562e+09
3,maharashtra,2019,2,Financial Services,182840,4.529164e+07
4,maharashtra,2019,2,Others,1170993,7.652283e+08

In [3]:
d = {
    'data': {
        'from': 1577817000000,
        'to': 1585333800000,
        'transactionData': [
            {
                'name': 'Merchant payments',
                'paymentInstruments': [
                    {
                        'type': 'TOTAL',
                        'count': 132970737,
                        'amount': 40374401933.52864
                    }
                ]
            }
        ]
    }
}

d['data']['transactionData'][0]['paymentInstruments'][0]['count']

132970737

# ***Aggregated Insaurance***

In [8]:
path2 = "/content/pulse/data/aggregated/insurance/country/india/state"

agg_insurence_state_list = os.listdir(path2)

print(agg_insurence_state_list)

col2 = {
    'State':[],
    'Year':[],
    'Quarter':[],
    'insurence_type':[],
    'insurence_count':[],
    'insurence_amount':[]
}

for i in agg_insurence_state_list:

    p_i = path2 + "/" + i

    agg_yr = os.listdir(p_i)

    for j in agg_yr:

        p_j = p_i + "/" + j

        agg_year_quarter = os.listdir(p_j)

        for k in agg_year_quarter:

            p_k = p_j + "/" + k

            data = open(p_k,'r')

            D = json.load(data)

            for z in D['data']['transactionData']:

                Name = z['name']

                count = z['paymentInstruments'][0]['count']

                amount = z['paymentInstruments'][0]['amount']

                col2['insurence_type'].append(Name)

                col2['insurence_count'].append(count)

                col2['insurence_amount'].append(amount)

                col2['State'].append(i)

                col2['Year'].append(j)

                col2['Quarter'].append(int(k.strip('.json')))

print(col2)

['maharashtra', 'uttarakhand', 'punjab', 'puducherry', 'gujarat', 'karnataka', 'delhi', 'andaman-&-nicobar-islands', 'tamil-nadu', 'bihar', 'andhra-pradesh', 'lakshadweep', 'meghalaya', 'rajasthan', 'chhattisgarh', 'arunachal-pradesh', 'himachal-pradesh', 'tripura', 'goa', 'haryana', 'uttar-pradesh', 'mizoram', 'west-bengal', 'madhya-pradesh', 'telangana', 'dadra-&-nagar-haveli-&-daman-&-diu', 'odisha', 'assam', 'sikkim', 'nagaland', 'chandigarh', 'jharkhand', 'ladakh', 'kerala', 'jammu-&-kashmir', 'manipur']

In [9]:
agg_insurence_state_list = pd.DataFrame(col2)

agg_insurence_state_list.head()

,State,Year,Quarter,insurence_type,insurence_count,insurence_amount
0,maharashtra,2021,2,Insurance,70381,46763103.0
1,maharashtra,2021,4,Insurance,82423,93262227.0
2,maharashtra,2021,3,Insurance,52268,41313307.0
3,maharashtra,2021,1,Insurance,55792,33137753.0
4,maharashtra,2022,2,Insurance,80935,104603934.0